name: textfields_dropdownbuttons
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  telephone_check: ^0.0.4
  validated: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
